services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    #image: ghcr.io/nikolajjmusatov/backend:latest
    container_name: backend
    depends_on:
      - postgres
    networks:
      - backend_net_postgres
      - backend_net_mongo
    env_file:
      - backend/.env
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    #image: ghcr.io/nikolajjmusatov/frontend:latest
    container_name: frontend
    networks:
      - backend_net_postgres
      - backend_net_mongo
    volumes:
      - frontend_dist:/app/dist
    env_file:
      - frontend/.env

  postgres:
    image: postgres:14
    container_name: postgres
    networks:
      - backend_net_postgres
    env_file:
      - postgres/.env
    volumes:
      #- ./_volume/postgres/postgres-init.sql:/docker-entrypoint-initdb.d/postgres-init.sql
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    env_file:
      - pgadmin/.env
    volumes:
      - pgadmin-data:/var/lib/pgadmin/data
    ports:
      - 8080:80
    networks:
      - backend_net_postgres
    depends_on:
      - postgres
    restart: unless-stopped

  mongo:
    image: mongo:latest
    container_name: mongo
    networks:
      - backend_net_mongo
    env_file:
      - mongodb/.env
    volumes:
      - ./_volume/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - db:/data/db
    restart: unless-stopped

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    ports:
      - 8081:8081
    depends_on:
      - mongo
    env_file:
      - mongo-express/.env
    volumes:
      - mongo-express-data:/var/lib/mongo-express/data
    networks:
      - backend_net_mongo
    restart: unless-stopped

  nginx:
    image: nginx
    ports:
      - 80:80
    networks:
      - backend_net_postgres
      - backend_net_mongo
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - frontend_dist:/var/www/frontend:ro

networks:
  backend_net_postgres:
  backend_net_mongo:

volumes:
  pgdata:
  pgadmin-data:
  frontend_dist:
  db:
  mongo-express-data: