services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    #image: ghcr.io/nikolajjmusatov/backend:latest
    container_name: backend
    depends_on:
      - postgres
    networks:
      - backend_net_postgres
    env_file:
      - backend/.env
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    #image: ghcr.io/nikolajjmusatov/frontend:latest
    container_name: frontend
    networks:
      - backend_net_postgres
    restart: unless-stopped
    volumes:
      - frontend_dist:/app/dist
    env_file:
      - frontend/.env

  postgres:
    image: postgres:14
    container_name: postgres
    networks:
      - backend_net_postgres
    env_file:
      - postgres/.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    env_file:
      - pgadmin/.env
    volumes:
      - pgadmin-data:/var/lib/pgadmin/data
    ports:
      - 8080:80
    networks:
      - backend_net_postgres
    depends_on:
      - postgres
    restart: unless-stopped

  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    networks:
      - backend_net_postgres
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - frontend_dist:/var/www/frontend:ro

networks:
  backend_net_postgres:

volumes:
  pgdata:
  pgadmin-data:
  frontend_dist: