version: '3.1'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - 3000:3000
    depends_on:
      - postgres
      - mongo
    networks:
      - backend_net_postgres
      - backend_net_mongo
    env_file:
      - backend/.env
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - 3001:80
    networks:
      - frontend_net
    env_file:
      - frontend/.env
    restart: unless-stopped
  
  postgres:
    image: postgres:14
    container_name: postgres
    networks:
      - backend_net_postgres
    ports:
      - 5432:5432
    env_file:
      - postgres/.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  mongo:
    image: mongo:latest
    container_name: mongo
    networks:
      - backend_net_mongo
    ports:
      - 27017:27017
    env_file:
      - mongodb/.env
    volumes:
      - mongo-data:/var/lib/mongo/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    env_file:
      - pgadmin/.env
    volumes:
      - pgadmin-data:/var/lib/pgadmin/data
    ports:
      - 8080:80
    networks:
      - backend_net_postgres
    depends_on:
      - postgres
    restart: unless-stopped
    
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    ports:
      - 8081:8081
    depends_on:
      - mongo
    env_file:
      - mongo-express/.env
    volumes:
      - mongo-express-data:/var/lib/mongo-express/data
    networks:
      - backend_net_mongo
    restart: unless-stopped

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - frontend_net
      - backend_net_postgres
      - backend_net_mongo
    depends_on:
      - backend
      - frontend
    restart: unless-stopped

networks:
  backend_net_postgres:
  backend_net_mongo:
  frontend_net:

volumes:
  postgres-data:
  pgadmin-data:
  mongo-data:
  mongo-express-data: